"""Generate stub engine files for custom imported problems."""

import os
from typing import Dict

# Algorithms that typically operate on a grid/map
_MAP_BASED_ALGOS = {"bfs", "dijkstra", "dfs", "topo", "mst"}

# Algorithms that typically operate on abstract data structures
_DATA_BASED_ALGOS = {"uf", "dp", "greedy", "binary", "bitmask"}


def _map_based_stub(algo: str, custom_id: str) -> str:
    """Stub template for grid / graph traversal algorithms."""
    return f'''\
"""Engine stub for custom problem: {custom_id}  (algorithm: {algo})

This file was auto-generated by the WARFRONT importer.
Fill in the sections marked with TODO to connect your problem to the
WARFRONT visualizer.

Layout conventions:
  build_map()        — construct the GameMap and mark start/goal
  get_test_data()    — return auxiliary dict (empty dict is fine for map-only problems)
  visualize_result() — convert solve() output to a list of (snapshot, label, info) tuples
"""

import random
from map import Terrain, UnitType


def build_map():
    """Return (GameMap, start_tuple, goal_tuple).

    TODO: Replace the random terrain generation below with the map that
          matches your problem constraints.
    """
    from map import GameMap

    rows, cols = 12, 12
    gmap = GameMap(rows, cols)

    start = (0, 0)
    goal = (rows - 1, cols - 1)

    # TODO: Set terrain, walls, and weighted cells as needed.
    for _ in range(20):
        r = random.randint(0, rows - 1)
        c = random.randint(0, cols - 1)
        if (r, c) not in (start, goal):
            gmap.set_terrain(r, c, Terrain.WALL)

    gmap.set_terrain(start[0], start[1], Terrain.PLAIN)
    gmap.set_terrain(goal[0], goal[1], Terrain.PLAIN)
    gmap.place_unit(start[0], start[1], UnitType.ALLY)
    gmap.place_unit(goal[0], goal[1], UnitType.TARGET)

    return gmap, start, goal


def get_test_data():
    """Return auxiliary test data passed as the second argument to solve().

    TODO: Add any extra inputs your solve() function needs beyond the map,
          or leave as an empty dict if the map is sufficient.
    """
    return {{}}


def visualize_result(gmap, result):
    """Convert the return value of solve() into animation steps.

    Each step is a 3-tuple:
        (snapshot(gmap), label_string, info_string)

    TODO: Adapt this to match the structure returned by your solve().
          The example below expects result to be a list of (row, col) tuples.
    """
    from core import snapshot

    if not result:
        return [(snapshot(gmap), "No path found", "solve() returned empty — check your logic")]

    steps = []
    for i, (r, c) in enumerate(result):
        gmap.grid[r][c].visited = True
        gmap.grid[r][c].in_path = True
        if i == len(result) - 1:
            steps.append((snapshot(gmap), "Goal reached", f"Steps: {{len(result)}}"))
        else:
            steps.append((snapshot(gmap), f"Step {{i}}: ({{r}},{{c}})", f"algorithm: {algo}"))
    return steps
'''


def _data_based_stub(algo: str, custom_id: str) -> str:
    """Stub template for data-structure / abstract algorithms."""
    return f'''\
"""Engine stub for custom problem: {custom_id}  (algorithm: {algo})

This file was auto-generated by the WARFRONT importer.
Fill in the sections marked with TODO to connect your problem to the
WARFRONT visualizer.

Layout conventions:
  build_map()        — returns a minimal GameMap (required by the framework even for
                       data-only problems)
  get_test_data()    — return the primary input dict consumed by solve()
  visualize_result() — convert solve() output to a list of (snapshot, label, info) tuples
"""


def build_map():
    """Return a minimal (GameMap, start, goal) triple.

    For data-based algorithms the map is rarely visualized, but the
    WARFRONT framework still requires this function to be present.
    """
    from map import GameMap
    return GameMap(12, 12), (0, 0), (11, 11)


def get_test_data():
    """Return the primary test data dict consumed by solve().

    TODO: Replace the placeholder below with inputs that match your
          problem statement.

    Example for {algo}:
        return {{
            # TODO: add your problem-specific keys and values here
            "input": [],
        }}
    """
    return {{
        "input": [],  # TODO: define your test data
    }}


def visualize_result(gmap, result):
    """Convert the return value of solve() into animation steps.

    Each step is a 3-tuple:
        (snapshot(gmap), label_string, info_string)

    TODO: Update the label and info strings to meaningfully describe
          what your algorithm computed.
    """
    from core import snapshot
    return [
        (snapshot(gmap), "{algo.upper()} complete", f"Result: {{result}}")
    ]
'''


def generate_engine_stub(algo: str, custom_id: str) -> str:
    """Return Python source for engines/custom_{custom_id}.py.

    Args:
        algo:      Algorithm identifier (e.g. "bfs", "dp", "unknown").
        custom_id: Unique identifier for this custom problem (used in
                   the filename and as a human-readable label).

    Returns:
        A string containing the complete Python source of the stub file.
    """
    algo_lower = algo.lower()

    if algo_lower in _DATA_BASED_ALGOS:
        return _data_based_stub(algo_lower, custom_id)

    # Default to map-based (covers "bfs", "dijkstra", "dfs", "topo", "mst", "unknown")
    return _map_based_stub(algo_lower, custom_id)


def write_engine_stub(algo: str, custom_id: str, engines_dir: str) -> str:
    """Write a stub engine file into engines_dir and return the file path.

    Args:
        algo:        Algorithm identifier string.
        custom_id:   Unique ID for this custom problem.
        engines_dir: Absolute path to the engines/ directory.

    Returns:
        Absolute path of the written stub file.

    Raises:
        OSError: If the directory cannot be created or the file cannot be written.
    """
    os.makedirs(engines_dir, exist_ok=True)
    stub_source = generate_engine_stub(algo, custom_id)
    filename = f"custom_{custom_id}.py"
    dest = os.path.join(engines_dir, filename)

    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(stub_source)

    return dest
